# Usage:  $ conda env create -f environment.yml
# Please add to the pip section the packages that drop the error "ResolvePackageNotFound"
name: HMCTuning
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.4
  - pytorch
  - torchvision
  - pip
  - pip:
      - pytorch-lightning
      - matplotlib
      - scipy
      - pandas
      - openpyxl
      - termcolor
      - xlrd
      - seaborn
      - h5py
      - scikit-learn