L: 5
T: 10
arch: base
batch_size: 128
chains: 1
data_path: ../data/
dim_h: 512
dim_x: 784
latent_dim: 2
likelihood: bernoulli
lr: 0.001
lr_decoder: 0.001
lr_encoder: 0.001
lr_hmc: 0.001
lr_pre: 0.001
lr_scale: 0.01
pre_steps: 45000.0
samples_MC: 1
sksd: 1
update_s_each: 10
variance: 0.1
